---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-aws-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
  - repoURL: https://github.com/fabio-mrocha/argocd-crossplane.git
    targetRevision: main
    path: crossplane/provider-config
  destination:
    name: in-cluster
    namespace: crossplane-providers
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
